### ISSUE TITLE
Threading question

### ISSUE THREAD

**Issue by NebriBlackwing** [NaamloosDT/DiscordSharp_Starter#3]
Looking over the program.cs in the starter code, my assumption is that everything is running off the same blocking thread.

If user A sends in a message that my bot starts to process, and user B sends in a second message, my assumption is that this is very open to collisions. Will user B's request be lost if the thread is still busy? or will it all be processed in order once User A's request has been resolved?

**Comment by suicvne** [comment]
User A sends message --> processing, thread blocks
User B sends message while processing --> socket hasn't yet received it
Processing completes --> thread updates --> message is received.

Just don't do anything _too_ intensive inside this thread because you could
lose connection due to keepalives not firing off. Generally, I just run
connect in a separate thread but the creator of this project has chosen not
to do that.

**Comment by Naamloos** [comment]
At first i didn't really see a reason to run connect in a separate thread. I'm working on it :)

**Comment by Naamloos** [comment]
`client.Connect` is now executed in a separate thread.

**Comment by suicvne** [comment]
Wasn't fully necessary to do that but it doesn't hurt to anyway ;)

**Comment by Naamloos** [comment]
Exactly as you say, wouldn't hurt :)

**Comment by NebriBlackwing** [comment]
Excellent, thank you very much. I'll defitely review the additions and pull this into my project a little later once DiscordSharp becomes more stable. :+1:

**Comment by Naamloos** [comment]
No problem
